spring:
  datasource:
    url: jdbc:mysql://123.57.78.6:3306/psychology?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

  redis:
    database: 0
    host: 123.57.78.6
    port: 6379
    password: 235610
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-wait: 2000
        max-idle: 500
        min-idle: 8
  mvc:
    static-path-pattern: /static/**
app:
  jwtSecret: e07e56d6258c
  jwtExpirationInMs: 604800000
